image: golang:latest

before_script:
  - make deps
#  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.27.0

stages:
  - build

compiled_dev:
  stage: build
  script:
#    - make all
    - make build
#    - make build-bot
  after_script:
    - bash <(curl -s https://codecov.io/bash) -t "${CODECOV_TOKEN}"
  artifacts:
    paths:
      - propolis
      - propolis_x86
      - propolis_darwin
      - propolis_windows.exe
#      - propolis-bot
    name: "propolis-dev-${CI_COMMIT_REF_NAME}"
    expire_in: 4 weeks
  except:
    - tags

compiled_release:
  stage: build
  script:
#    - make all
    - make build
#    - make build-bot
  after_script:
    - bash <(curl -s https://codecov.io/bash) -t "${CODECOV_TOKEN}"
  artifacts:
    paths:
      - propolis
      - propolis_x86
      - propolis_darwin
      - propolis_windows.exe
  #    - propolis-bot
    name: "propolis-${CI_COMMIT_REF_NAME}"
  only:
    - tags
