# Reference: https://github.com/golangci/golangci-lint

linters:
  enable-all: true
  disable:
    - gochecknoglobals
    - lll
    - maligned
    # TODO: enable and fix more things
    - deadcode
    - goconst
    - scopelint
    - gocyclo
    - structcheck
    - gosec
    - megacheck
    - errcheck
    - varcheck
    - gocritic
    - golint
    - goimports
    - prealloc
    - depguard
    - typecheck
    - wsl
    - godox
    - funlen
    - dogsled
    - gocognit
    - unparam # re-enable later
    - testpackage
    - gomnd
    - goerr113
    - nestif
    - gochecknoinits
